### ISSUE TITLE
up: Error during image registry authentication

### ISSUE THREAD

**Issue by FabianK1991** [covexo/devspace#216]
Deploying a private registry into a kubernetes cluster causes the error during `devspace up`:

```
Error during image registry authentication: Error response from daemon: Get https://10.0.34.147:5000/v1/users/: http: server gave HTTP response to HTTPS client
```

**Comment by LukasGentele** [comment]
works for registries with an ingress and TLS. Added a warning.

**Comment by ADustyOldMuffin** [comment]
For anyone who might show up here in the future. This also appears if your entry in the `/etc/hosts` file is incorrect.
