### ISSUE TITLE
minor issue - DevSpace Documentation site image error

### ISSUE THREAD

**Issue by leetskil** [covexo/devspace#258]
DevSpace Documentation site image error

images not showing in the doc site https://devspace.covexo.com/

**Comment by FabianK1991** [comment]
Thanks for reporting this issue! We'll take a look into this and fix it as soon as possible.

**Comment by FabianK1991** [comment]
Should be fixed, the images not showing were left overs from the default docusaurus page that shouldn't be shown anyway, so I removed this part of the documentation
