### ISSUE TITLE
Error when using kaniko as a building engine without docker daemon running.

### ISSUE THREAD

**Issue by KaelBaldwin** [covexo/devspace#307]
First off great job guys, this is a really cool project.

I'm running Windows 10 and I have my project configured to use kaniko as the build engine and I'm using my own private registry.

I have docker for windows installed but not running. (I'm hoping other developers without docker don't have to install docker and can just use kaniko as the build engine instead to get started working on our project. For that reason I'm leaving docker off.)

When I run devspace up, I get the following:

>>> [INFO]   Building image 'kael/devspace' with engine 'kaniko'
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
[FATAL]  Error during image registry authentication: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/auth: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by FabianKramm** [comment]
Thanks for creating this issue! I totally agree using docker on windows is still a pain. DevSpace should work without docker using kaniko, however the behavior currently assumes that you either define your private registry user/pass in the ./devspace/config.yaml under registries[].auth or as a fallback that you have docker installed and the credentials for the registry are stored there (if docker is not found, you receive the above mentioned error). I assume that you have created a pull secret yourself in your cluster to authenticate to your private registry.  

Personally I would suggest another option, where we could add a config option `pullSecret` to the config section `images[].build.kaniko` where you can specify the custom pullSecret kaniko should use to authenticate to the registry. So I will flag this issue as a feature request.

**Comment by FabianKramm** [comment]
@KaelBaldwin Ah I see, yes this is a mistake in the full config.yaml example, thanks for pointing that out! No it is the same for internal and private registries, `user` was used before version 2.0.0 and we probably forgot to change it in the documentation!  

I changed the documentation from user to auth and added an additional example.
