### ISSUE TITLE
devspace up (helm client) doesn't deploy if helm chart hasn't changed and the chart is not currently deployed.

### ISSUE THREAD

**Issue by KaelBaldwin** [covexo/devspace#325]
Steps to reproduce issue:
1. Make sure you are using the helm client (not sure if this happens with the kubectl client)
2. run `devspace up`
3. run `devspace down`
4. Don't change anything.
5. Run `devspace up`

Notice it says "successfully deployed..." but nothing was actually deployed.

I believe this is because it checks the generated config file to see if the chart has changed to determine if it should be deployed or not, but does not check if the chart is actually currently deployed.

This leads to you either having to delete the generated config file, or just change something insignificant to get `devspace up` to work again.

**Comment by LukasGentele** [comment]
Thanks for reporting. I think you are right. I would suggest two things to solve the issue:

1. When running `devspace down`, the chartHashs in generated.yaml should be removed.
2. When running `devspace up`, we should additionally check with helm if there is a release actually deployed before skipping the deployment.

Any other suggestions? @FabianKramm?
