### ISSUE TITLE
Print error if config file contains invalid keys

### ISSUE THREAD

**Issue by FabianKramm** [covexo/devspace#350]
The current state in the config allows unspecified keys (e.g. cotnainerPath instead of containerPath etc.) and usually does not print an error on parsing. This often leads to unexpected behavior because a key was accidentally mistyped but has no effect during runtime. Hence we should validate the config on loading it and fatal out (or atleast print an error) if a disallowed key is found.

**Comment by LukasGentele** [comment]
related to #170
