### ISSUE TITLE
devspace reset: ask for deleting kubernetes context from ./kube/config

### ISSUE THREAD

**Issue by LukasGentele** [covexo/devspace#351]
**Is your feature request related to a problem?**  
When running `devspace up`, the user is asked if the kubernetes context should be added to .kube/config but when running `devspace reset`, users are not asked if this context should be removed again.

**Which solution do you suggest?**  
Asking the user: `Should the Kubernetes context "XXXXXXX" be removed from ~/.kube/config? (y/n)`

**Which alternative solutions exist?**  
/

**Additional context**  
/

/kind feature

**Comment by FabianKramm** [comment]
Implemented in #363
