### ISSUE TITLE
Remove exit-after-deploy flag for devspace up

### ISSUE THREAD

**Issue by LukasGentele** [covexo/devspace#352]
This flag has been obsolete since `devspace deploy` was introduced.

**Comment by FabianKramm** [comment]
@LukasGentele I think we should keep the flag since `devspace deploy` does not behave exactly the same as `devspace up` (e.g. in helm deployments the dev override config flag is only used in the up command)

**Comment by LukasGentele** [comment]
Ok, makes sense. Thanks for clarifying.
