### ISSUE TITLE
Automatic Redeploy when the Dockerfile or Kubernetes Manifests Change

### ISSUE THREAD

**Issue by ALCarden** [covexo/devspace#387]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Monitor the Dockerfile and Manifests for changes, on dockerfile changes, rebuild, tag and update the image in the manifest then apply.

**Which alternative solutions exist?**  

**Additional context**  
Currently dockerfile and manifest changes are not detected and we have to do a 'devspace down' and then 'devspace' to get the changes applied.

Google Skaffold detects the changes and applies them automatic.

/kind feature

**Comment by FabianKramm** [comment]
@ALCarden I implemented this feature and it is activated by default. In addition I added a config option to devspace.deployments[].autoReload & images[].autoReload to disable the behavior.

**Comment by FabianKramm** [comment]
Available in 2.4.0
