### ISSUE TITLE
Provide feature that causes image rebuilding and deployment when files specified in configuration change.

### ISSUE THREAD

**Issue by ALCarden** [covexo/devspace#389]
**Is your feature request related to a problem?**  
Currently our development stack is nodejs based, when we change our package.json it gets synced but the changes are not applied because npm install is not re-run in the container.

We can (and do disable) the sync of package.json but we to do delete the generated.yaml to force a rebuild of the image which contains the npm install run task.

**Which solution do you suggest?**  
Have a new image configuration section consisting of an array of file globs which on change cause the docker file to be rebuilt, the tag to be updated and the configuration to be redeployed.

or

When specific file changes are detected for sync provide a property where we can specify a script to run in the container, e.g. to cause the application running in the container to take some action (development purposes only)

**Which alternative solutions exist?**  
Manual: Remove the generated.yaml

**Additional context**  

/kind feature

**Comment by FabianKramm** [comment]
@ALCarden I implemented this feature and added a new config option (your first suggestion) to the config under devspace.autoReload.paths where you can specify paths that devspace will watch. On changes to those globs devspace will rebuild and redeploy.  

I also added a new example that shows how to use this feature (example [reload-instead-of-sync](https://github.com/covexo/devspace/tree/master/examples/reload-instead-of-sync))

**Comment by FabianKramm** [comment]
Available in 2.4.0

**Comment by geoidesic** [comment]
The example is a dead link

**Comment by FabianKramm** [comment]
@geoidesic Yes sorry the example was renamed to [redeploy-instead-of-hot-reload](https://github.com/devspace-cloud/devspace/tree/master/examples/redeploy-instead-of-hot-reload)
