### ISSUE TITLE
Switching git branches on host causes files which exist in branch1, but not branch2, to be downloaded from the container.

### ISSUE THREAD

**Issue by KaelBaldwin** [covexo/devspace#410]
**What happened?**  
While working in a devspace synced directory, I finished creating new files and committed changes to git branch1. Moving on to my next task, on my host, I used my IDE to switch back to the base branch which did not contain the changes. I noticed that the files I had created in branch1 were then downloaded from the container.

**What did you expect to happen instead?**  
I did not expect files being removed by the git checkout process to still exist on the container and then get synced back to my host machine, causing me to have to manually delete them.

**How can we reproduce the bug?** (as minimally and precisely as possible)  
I would think this could be reproduced with any repo.

1. Create a new branch in any repo.
1. Run `devspace up` on your host
1. Once everything is synced, create some files and commit them to your new branch.
1. On your host machine, git checkout back to your original branch.
1. Check for untracked files on your host machine. You should see the files you created after they have a moment to sync.

**Local Environment:**  
- Operating System: windows
- Deployment method: helm

**Kubernetes Cluster:**  
- Cloud Provider: baremetal (provisioned via rancher/gke)
- Kubernetes Version: 

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

**Comment by FabianKramm** [comment]
Thanks for opening this issue! So I tried to reproduce the issue, but it worked for me, the files were deleted on the remote machine instead of downloaded again.  

Do you create the files in step 3 on the host machine or remotely? Could you post the .devspace/log/sync.log when the issue appeared here?

**Comment by KaelBaldwin** [comment]
I created the files in step three on the host machine, after 5 they are present on both.

Working on getting the logs now.

**Comment by KaelBaldwin** [comment]
@FabianKramm 

I'm sorry, while playing around with it more, I think this is caused by the connectivity issues I've been having with the sync process. I'm often having an issue where the devspaces upstream sync kubectl shell is losing connectivity and I think causing it to either just miss the "EndAck" message from the container or it's getting cut off entirely (without throwing an error and killing devspaces upstream sync kubectl shell). I haven't been able to determine which of those two are happening yet.

Anyways, because the upstream process gets locked up, I must have killed the process, switched branches and then ran devspace up. In that scenario, devspace sees the files that were on the container from the previous branch (since the upstream process was locked up it never removed the files) and downloads them.

I think this is working as intended and fixing the sync issues by making the sync process more robust will solve this as well. I'll open up another issue or feature request for that once I figure out exactly where the problem is occuring.

Thanks.
