### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by haf** [covexo/devspace#417]
After trying the quickstart with a local minikube on xhyve, I have some feedback.

Getting started worked well. I'm concerned that I had to fill out credentials for docker hub, because I never want to push our code-base as a public docker container, and I'm not purchasing private docker storage. It would be better to ask me how I want to store container I create.

Neither the quick start guide, nor the "next steps" discuss how to add more services; when perusing the examples, you have a mysql+PHP example, which sort of is enough, but I can't find docs about multiple services from my own repo (which is what I need).

I can't find good information on why Helm is used in devspace. I can't find information about how to configure ingress or load balancing and networking (if any), nor how DNS and other infrastructure services work in devspace.

After playing around a bit: nice experience with the hot reloading, btw; I do `devspace down`, but it only removes tiller, not the deployed pod of the quickstart-nodejs app (as reported by `kubectl get pods`). There are no docs on how to remove the runtime artifacts from minikube/k8s. Also, our environment is gcloud; and there are no docs on how to use its hosted kube/hosted docker registry (instead of hub.docker.com).

As I wanted to kill everything started, and that didn't work, I try `devspace up` again, in the same quickstart folder. Now it fails with `[FATAL]  Error deploying devspace: Error deploying devspace-default: Error creating helm client: Waiting for tiller timed out`, after a few minutes.

Furthermore, reading your "about" link on your home page is broken. And in your ToS, the link to the Privacy Policy is broken. And there's nothing about you guys in the README, nor what you charge for. The ToS seems adapted for a monthly subscription service, but there's nothing on the site that specifies what you charge for. This uncertainty for me as a first-time user. I simply can't see if you're trolling me — selling of my laptop configuration to third parties — or if you're trying to create a sort of developers-cloud-service, like Hashicorp is trying to. (I had to resort to reading your code-base to verify that it's not bad code, before installing, especially since you have a curl-from-internet type of installation instead of a `brew install devspace`, like I'd expect a mature project to have)

I also chose a different namespace, since I run a few different projects on my minikube; chose `devspace-sample` as the ns. This was nicely written into the yaml-config file. However, when doing the up-down-up sequence of commands I mentioned above, tiller was deployed to both `default` and `devspace-default`.

<img width="504" alt="image" src="https://user-images.githubusercontent.com/193115/49651575-e2c88880-fa2f-11e8-9e1c-0cc6a8f9328e.png">

**What happened?**  
Bad onboarding experience

**What did you expect to happen instead?**  
Better onboarding

**How can we reproduce the bug?** (as minimally and precisely as possible)  
Do your own quickstart, do `devspace down`, then `kubectl get pods`. You haven't successfully shut down the devspace.

**Local Environment:**  
- Operating System: mac
- Deployment method: helm

**Kubernetes Cluster:**

- Cloud Provider: minikube
- Kubernetes Version: 

```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:38Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by LukasGentele** [comment]
Hi @haf! Thanks for your detailed description. Our team highly appreciates your feedback. 

- I created several issues based on your input: #418 #420 #421
- Regarding network configuration, I would recommend taking a look at the official k8s docs: https://kubernetes.io/docs/concepts/cluster-administration/networking/
- Your issue with tiller timeout and devspace down/up should be resolved in release v2.4.1 (thanks for pointing us to this issue. That was really helpful!)
- Our "about page" is currently being built, so it might take a couple of weeks until we add the correct links to the devspace-cloud.com website. Then, you will find more details about us and what drives us to build developer tooling for cloud native technologies.

I am sorry that we did not provide all the information you needed earlier but this is still a very young project. We work hard to improve it every day and there is a lot more to come in terms of documentation, step-by-step guides etc. I am closing this for now as we have the referenced issues but if you have any further input, feel free to open the issue again or join us on slack: http://slack.devspace-cloud.com
