### ISSUE TITLE
Minikube: Skip question for image registry

### ISSUE THREAD

**Issue by LukasGentele** [covexo/devspace#418]
**Is your feature request related to a problem?**  
No

**Which solution do you suggest?**  
Using minikube currently skips the image push because the image is built with the docker daemon inside the minikube VM. The init function, however, still asks for the image registry which is not important anyways. We should skip the question in case of minikube.

**Which alternative solutions exist?**  
-

**Additional context**  
-

/kind feature

**Comment by FabianKramm** [comment]
Fixed with v2.5.0
