### ISSUE TITLE
Feature: option to open multiple terminals on devspace up

### ISSUE THREAD

**Issue by musicformellons** [covexo/devspace#449]
I tried giving labels ```feature: devspace-default``` to multiple containers, but only one is started when doing ```devspace up```. Would be nice to have this feature as an option.

**Comment by LukasGentele** [comment]
Thanks for your feature proposal. I am not really sure if this can be done, though. The issue with that suggestion is that the CLI tool would have to open other terminals outside of the one the CLI tool is run in. That is not a very common behavior for a CLI tool. On top of that I imagine that being quite hard to implement that across different operating systems.

**Comment by musicformellons** [comment]
ok, thanks for clarifying.
